// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import FrequentlyAskedQuestions from './FrequentlyAskedQuestions';
import Hero from './Hero';
import MainMenuItem from './MainMenuItem';
import Spotlight from './Spotlight';

export {
	Content,
	FrequentlyAskedQuestions,
	Hero,
	MainMenuItem,
	Spotlight,
};

export const components = {
	content: Content,
	frequently_asked_questions: FrequentlyAskedQuestions,
	hero: Hero,
	main_menu_item: MainMenuItem,
	spotlight: Spotlight,
};
