// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import MainMenuItem from './MainMenuItem';
import Spotlight from './Spotlight';

export {
	Hero,
	MainMenuItem,
	Spotlight,
};

export const components = {
	hero: Hero,
	main_menu_item: MainMenuItem,
	spotlight: Spotlight,
};
